name: Run Tests and Save Results

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests and save results
        run: |
          mkdir -p test-history
          npm run test

      - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
          name: test-result-${{ github.run_number }}
          path: test-history/results.json
